---
title: "RNAseq Validation Set"
subtitle: Validation of the 19-genes model on the palomero et al (Nat Gen 2014) RNAseq - dbGap phs000689.v1.p1 
  series
output:
  html_document: default
  html_notebook: default
---
Built with R version:  
`r getRversion()`

```{r setup, include=FALSE}

library("AnnotationDbi")
library("org.Hs.eg.db")
library("DESeq2")
library("dplyr")
library("ggplot2")
library("vsn")
library("pheatmap")
library("RColorBrewer")
library("PoiClaClu")
library("biomaRt")
library("ConsensusClusterPlus")
library("MASS")

```


## Ensembl Library

For  gene convertion from array to HUGO

```{r}
ensembl = useMart( "ensembl", dataset = "hsapiens_gene_ensembl" )

gene<- c("ADRA2A","AL441992.1","ARHGEF10","C3","COL4A4", "DZIP1",
         "EFNB2","HS3ST3A1","ID2","NETO2","OSMR","PRRX1","ROBO1",
         "SLC5A3","XKR4","YAP1", "TNFRSF8","BATF3","TMOD1")   
hgnc_swissprot <- getBM(attributes=c('ensembl_gene_id','ensembl_transcript_id','hgnc_symbol','hgnc_id'),filters = 'hgnc_symbol', values = gene, mart = ensembl)
ens<- unique(hgnc_swissprot[,c("ensembl_gene_id","hgnc_symbol")])

```

## Upload data

```{r cars}

setwd("/Volumes/fm6/PTCL_NOS/PTCL_GEP/palomero_rna_data/")

### list the extracted 19-genes

### upload the RNAseq raw data
final_rna<- read.delim("RNA_seq_palomero.txt",sep="\t", stringsAsFactors = F, header=T)

db_palo<- final_rna[rownames(final_rna) %in% ens$ensembl_gene_id,]

setwd("/Volumes/fm6/PTCL_NOS/PTCL_GEP/palomero_rna_data/")
clin<- read.delim(file = "hist_palomero.txt", sep="\t", header=T, stringsAsFactors = F )
annotation_col<-clin[,c("Sample","Unpublished")]
annotation_col$Sample<- gsub("CN","", annotation_col$Sample)
rownames(annotation_col)<- annotation_col$Sample
final_rna2<- final_rna[,-14] ### remove the case with unknwon histology



```

## RNAseq normalization

You can also embed plots, for example:

```{r}

#################################################################################################################
  
### https://master.bioconductor.org/packages/release/workflows/vignettes/rnaseqGene/inst/doc/rnaseqGene.html#starting-from-count-matrices   

#################################################################################################################

ddsMat <- DESeqDataSetFromMatrix(countData = final_rna2,
                                 colData = annotation_col,
                                 design = ~ Unpublished)
dds <- ddsMat[ rowSums(counts(ddsMat)) > 1, ]
lambda <- 10^seq(from = -1, to = 2, length = 1000)
cts <- matrix(rpois(1000*100, lambda), ncol = 100)


meanSdPlot(cts, ranks = FALSE)
log.cts.one <- log2(cts + 1)
meanSdPlot(log.cts.one, ranks = FALSE)
vsd <- vst(dds, blind = FALSE)
head(assay(vsd), 3)
rld <- rlog(dds, blind = FALSE) #### LONG RUN
head(assay(rld), 3)

dds <- estimateSizeFactors(dds)
df <- bind_rows(
  as_data_frame(log2(counts(dds, normalized=TRUE)[, 1:2]+1)) %>%
    mutate(transformation = "log2(x + 1)"),
  as_data_frame(assay(vsd)[, 1:2]) %>% mutate(transformation = "vst"),
  as_data_frame(assay(rld)[, 1:2]) %>% mutate(transformation = "rlog"))

colnames(df)[1:2] <- c("x", "y")  

ggplot(df, aes(x = x, y = y)) + geom_hex(bins = 80) +
  coord_fixed() + facet_grid( . ~ transformation)  

sampleDists <- dist(t(assay(vsd)))
sampleDists
sampleDistMatrix <- as.matrix( sampleDists )
rownames(sampleDistMatrix) <- paste( vsd$dex, vsd$cell, sep = " - " )
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
pheatmap(sampleDistMatrix,
         clustering_distance_rows = sampleDists,
         clustering_distance_cols = sampleDists,
         col = colors)

poisd <- PoissonDistance(t(counts(dds)))
samplePoisDistMatrix <- as.matrix( poisd$dd )
rownames(samplePoisDistMatrix) <- paste( dds$dex, dds$cell, sep=" - " )
colnames(samplePoisDistMatrix) <- NULL
pheatmap(samplePoisDistMatrix,
         clustering_distance_rows = poisd$dd,
         clustering_distance_cols = poisd$dd,
         col = colors)
plotPCA(vsd, intgroup = c("Unpublished"))
```


## Clustering

You can also embed plots, for example:

```{r}
edata3<- as.matrix((assay(rld))) #### vsd as data set small
edata<- edata3[rownames(edata3) %in% ens$ensembl_gene_id, ]

d<- data.matrix(edata)
d = sweep(d,1, apply(d,1,median,na.rm=T))
results = ConsensusClusterPlus(d,maxK=8,
                               pFeature=1,
                               clusterAlg="hc",
                               innerLinkage="ward.D2", 
                               finalLinkage="ward.D2", 
                               distance="euclidean", 
                               seed=123456789)
kk<- as.data.frame((results[[5]]$consensusClass)) ##### 4 significant cluster
kk$Sample<- rownames(kk)
colnames(kk)[1]<- "cluster"
table(kk$cluster)

```

```{r}
setwd("/Volumes/fm6/PTCL_NOS/PTCL_GEP/palomero_rna_data/")
clin<- read.delim(file = "ID_Subtype_palomero.txt", sep="\t", header=T, stringsAsFactors = F )
annotation_col2<-clin[,c("sampleID","Hist","DNMT3A","IDH2","RHOA","TET2")]
colnames(annotation_col2)[1:2]<-c("Sample","Hist")
rownames(annotation_col2)<- annotation_col2$Sample
annotation_col<-merge(kk,annotation_col2, by="Sample" )
annotation_col[is.na(annotation_col)]<-0
rownames(annotation_col)<- annotation_col$Sample
A <- function(x) (as.factor(as.character(x))) ##### lapply function for all columns to generate the relative contribution
annotation_col[,1:ncol(annotation_col)] = apply(annotation_col[,1:ncol(annotation_col)], 2, function(x) as.factor(as.character(x)))
annotation_col<- as.data.frame(annotation_col[,-1])
mycol_plus<- c(brewer.pal(11,"Paired"),brewer.pal(6,"Dark2"))
ann_colors = list(Hist=c( "AITL"="black","ALCL-ALKneg"="yellow","PTCL-NOS"="orange","ALCL-ALKpos"="dodgerblue"),
                  alk_status=c("1"="red","0"="grey95"),
                  cluster=c("1" = mycol_plus[4],"2" = mycol_plus[1],"3" = mycol_plus[5],"4" = mycol_plus[6],"5" =mycol_plus[7]),
                  DNMT3A = c("1"="red","0"="grey95"),
                  IDH2 = c("1"="red","0"="grey95"),
                  RHOA = c("1"="red","0"="grey95"),
                  TET2 = c("1"="red","0"="grey95")
                  )
edata3<- as.matrix((assay(rld)))
edata<- edata3[rownames(edata3) %in% ens$ensembl_gene_id, ]
hgnc_swissprot <- getBM(attributes=c('ensembl_gene_id','ensembl_transcript_id','hgnc_symbol','hgnc_id'),
                        filters = 'ensembl_gene_id', values =  rownames(edata), mart = ensembl)
ens<- unique(hgnc_swissprot[,c("ensembl_gene_id","hgnc_symbol")])
rownames(edata)<- ens$hgnc_symbol

library(pheatmap)
pheatmap(as.matrix( (edata)), annotation_col=annotation_col, annotation_colors = ann_colors, border_color="NA")

```

